# .github/workflows/douban.yml
name: douban
on:
  schedule:
  - cron: "10 * * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: ShaohanTian/doumark-action@master
      with:
        id: shaohanTian
        type: movie
        format: csv
        dir: ./data/douban

    - name: music
      uses: ShaohanTian/doumark-action@master
      with:
        id: shaohanTian
        type: music
        format: csv
        dir: ./data/douban

    - name: book
      uses: ShaohanTian/doumark-action@master
      with:
        id: shaohanTian
        type: book
        format: csv
        dir: ./data/douban

    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './data/douban'